from __future__ import annotations

from dataclasses import dataclass


AVAIL_AVAILABLE = "available"
AVAIL_PARTIAL = "partially_available"
AVAIL_UNAVAILABLE = "unavailable"
AVAIL_UNKNOWN = "unknown"


@dataclass(frozen=True)
class HandbookRuleDefinition:
    rule_id: str
    title: str
    ruleset: str
    handbook_source: str
    business_reason: str
    severity: str
    required_data_fields: tuple[str, ...]
    data_sources: tuple[str, ...]
    current_availability: str
    evaluation_logic: str
    pass_condition: str
    fail_condition: str
    insufficient_data_condition: str
    recommended_alert_recipient: str
    recommended_action: str
    delivery: str = "immediate"
    enabled_by_default: bool = True


def handbook_rule_matrix() -> list[HandbookRuleDefinition]:
    return list(HANDBOOK_RULES)


def handbook_rule_by_id(rule_id: str) -> HandbookRuleDefinition:
    return HANDBOOK_RULES_BY_ID[rule_id]


HANDBOOK_RULES: tuple[HandbookRuleDefinition, ...] = (
    HandbookRuleDefinition(
        "first_call_on_time_arrival",
        "First call on-time arrival",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: arrival protocol",
        "First calls set the customer expectation for the day and should start on time.",
        "high",
        ("arrival_window", "arrived_at"),
        ("ServiceTitan appointments", "ServiceTitan appointment assignments", "ServiceTitan technician time"),
        AVAIL_PARTIAL,
        "Compare arrived_at to arrival_window_start plus configured first-call grace minutes.",
        "Arrival is at or before the configured threshold.",
        "Arrival is after the configured threshold.",
        "Arrival window or arrival timestamp is unavailable.",
        "dispatcher channel",
        "Review dispatch timing, update the job record, and coach the technician if the late start was avoidable.",
    ),
    HandbookRuleDefinition(
        "arrival_outside_window_start_threshold",
        "Arrival outside window start threshold",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: arrival protocol",
        "Late arrivals need fast dispatch visibility and customer communication.",
        "medium",
        ("arrival_window", "arrived_at"),
        ("ServiceTitan appointments", "ServiceTitan appointment assignments", "ServiceTitan technician time"),
        AVAIL_PARTIAL,
        "Compare arrived_at to arrival_window_start plus SERVICE_TITAN_ARRIVAL_GRACE_MINUTES.",
        "Arrival is inside the configured arrival threshold.",
        "Arrival is outside the configured arrival threshold.",
        "Arrival window or arrival timestamp is unavailable.",
        "dispatcher channel",
        "Confirm whether the customer was notified and correct the dispatch record.",
    ),
    HandbookRuleDefinition(
        "missing_job_completion_notes",
        "Missing job completion notes",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: post-call",
        "Closeout notes provide the operational record for follow-up, billing, and quality review.",
        "medium",
        ("status", "notes"),
        ("ServiceTitan job summary", "ServiceTitan job notes"),
        AVAIL_AVAILABLE,
        "Require non-empty notes on closed jobs.",
        "Closed job has notes.",
        "Closed job has no notes.",
        "Job status or notes source is unavailable.",
        "dispatcher channel",
        "Add clear completion notes covering outcome, customer decision, and next step.",
    ),
    HandbookRuleDefinition(
        "job_notes_too_short",
        "Job notes too short",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: post-call",
        "Very short notes usually do not preserve enough customer and diagnostic context.",
        "medium",
        ("status", "notes"),
        ("ServiceTitan job summary", "ServiceTitan job notes"),
        AVAIL_AVAILABLE,
        "Compare trimmed note length to SERVICE_TITAN_MIN_NOTE_LENGTH.",
        "Notes meet the configured minimum length.",
        "Notes are present but shorter than the configured minimum.",
        "Job status or notes source is unavailable.",
        "dispatcher channel",
        "Expand the job notes with diagnostic result, options presented, decision, and next step.",
    ),
    HandbookRuleDefinition(
        "missing_required_photos",
        "Missing required photos",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: required photos/videos",
        "Photos support diagnostics, estimates, red flags, and warranty/vendor reviews.",
        "high",
        ("status", "photos"),
        ("ServiceTitan job attachments"),
        AVAIL_PARTIAL,
        "Require at least one photo when the attachment endpoint is available.",
        "Closed job has one or more photos.",
        "Closed job has no photos.",
        "Attachment/photo source is unavailable.",
        "technician manager",
        "Upload required equipment, label, thermostat, ductwork, damage, and faulty-part evidence or document why unavailable.",
    ),
    HandbookRuleDefinition(
        "missing_equipment_registration",
        "Missing equipment registration",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: equipment registration",
        "Equipment records make future diagnosis, warranty, and replacement recommendations reliable.",
        "high",
        ("status", "equipment"),
        ("ServiceTitan installed equipment"),
        AVAIL_PARTIAL,
        "Require equipment records with manufacturer, model, serial, location, and installed date when enabled.",
        "Equipment registration is present and complete, or the requirement is disabled.",
        "Equipment source is available but no complete equipment registration exists.",
        "Equipment source is unavailable.",
        "technician manager",
        "Add or update the equipment record with type, location, installed date, serial, manufacturer, and model.",
    ),
    HandbookRuleDefinition(
        "missing_hhr_or_service_form",
        "Missing HHR or service form",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: Home Health Report",
        "The Home Health Report is the documented customer-facing diagnostic summary.",
        "high",
        ("status", "hhr"),
        ("ServiceTitan forms", "ServiceTitan form submissions"),
        AVAIL_PARTIAL,
        "Require a form/submission matching configured HHR keywords when HHR is enabled.",
        "HHR or configured equivalent service form is completed, or the requirement is disabled.",
        "Forms source is available but no HHR/equivalent form is found.",
        "Forms source is unavailable.",
        "technician manager",
        "Complete the HHR/report card and add detailed comments with photo-backed red flags.",
    ),
    HandbookRuleDefinition(
        "missing_three_repair_options",
        "Missing three repair options",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: repair options",
        "Good/better/best options help customers choose and reduce incomplete presentations.",
        "high",
        ("status", "estimates"),
        ("ServiceTitan estimates", "ServiceTitan opportunities"),
        AVAIL_PARTIAL,
        "Compare estimate/opportunity count to SERVICE_TITAN_MIN_REPAIR_OPTIONS.",
        "At least the configured number of options exists.",
        "Fewer than the configured number of options exists.",
        "Estimate/opportunity source is unavailable.",
        "dispatcher channel",
        "Create or correct the option sheet with at least the configured number of customer options.",
    ),
    HandbookRuleDefinition(
        "missing_home_comfort_plan_option",
        "Missing Home Comfort Plan option",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: repair options",
        "The Home Comfort Plan should be part of the option set when configured.",
        "medium",
        ("status", "home_comfort_plan_option"),
        ("ServiceTitan estimates", "ServiceTitan opportunities"),
        AVAIL_PARTIAL,
        "Search estimate/opportunity text for configured Home Comfort Plan keywords.",
        "At least one option includes a configured Home Comfort Plan keyword, or the requirement is disabled.",
        "Options exist but none include a configured Home Comfort Plan keyword.",
        "Estimate/opportunity source is unavailable.",
        "dispatcher channel",
        "Add the Home Comfort Plan or documented equivalent to the option set when applicable.",
    ),
    HandbookRuleDefinition(
        "missing_same_day_estimate",
        "Missing same-day estimate",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: repair options",
        "Same-day estimates reduce abandoned repair recommendations and unclear customer decisions.",
        "medium",
        ("status", "same_day_estimate"),
        ("ServiceTitan estimates", "ServiceTitan opportunities"),
        AVAIL_PARTIAL,
        "Compare estimate creation date to job completion/modified date.",
        "At least one estimate was created the same day.",
        "Estimate source is available but no same-day estimate exists.",
        "Estimate dates are unavailable.",
        "dispatcher channel",
        "Create the same-day estimate or document why it could not be produced on the call.",
    ),
    HandbookRuleDefinition(
        "missing_price_authorization",
        "Missing price authorization",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: price authorization",
        "Signed authorization protects the customer, technician, and accounting record before work starts.",
        "high",
        ("status", "authorization"),
        ("ServiceTitan forms", "ServiceTitan attachments", "ServiceTitan invoices"),
        AVAIL_PARTIAL,
        "Require at least one authorization/signature indicator on closed jobs.",
        "Authorization/signature evidence exists.",
        "Authorization source is available but no authorization evidence exists.",
        "Authorization source is unavailable.",
        "accounting/office",
        "Add signed authorization or documented remote approval before billing review.",
    ),
    HandbookRuleDefinition(
        "missing_diagnostic_fee_when_repair_not_sold",
        "Missing diagnostic fee when repair not sold",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: diagnostic fee and payments",
        "The diagnostic/tune-up fee should be collected when no repair is sold unless a documented approval exists.",
        "high",
        ("status", "invoice_line_items"),
        ("ServiceTitan invoices", "ServiceTitan invoice items", "ServiceTitan job notes"),
        AVAIL_PARTIAL,
        "When repair_sold is false, require a diagnostic fee line item or approved waiver note.",
        "Diagnostic fee is present or an approved waiver reason is documented.",
        "No repair is sold and no diagnostic fee or approved waiver is present.",
        "Invoice items or repair-sold signal is unavailable.",
        "accounting/office",
        "Review the invoice, collect or add the diagnostic/tune-up fee, or document the approved waiver.",
    ),
    HandbookRuleDefinition(
        "diagnostic_fee_not_waived_when_repair_sold",
        "Diagnostic fee not waived when repair sold",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: diagnostic fee and payments",
        "The diagnostic fee should be waived when repair work is sold unless policy says otherwise.",
        "medium",
        ("status", "invoice_line_items"),
        ("ServiceTitan invoices", "ServiceTitan invoice items"),
        AVAIL_PARTIAL,
        "When repair_sold is true, fail only when a positive diagnostic fee amount is visible and no waiver is visible.",
        "Diagnostic fee is waived, absent, or not positively charged.",
        "Repair is sold and a positive diagnostic fee charge is visible without a waiver.",
        "Invoice item amounts or repair-sold signal is unavailable.",
        "accounting/office",
        "Review whether the diagnostic fee should be waived or corrected on the invoice.",
    ),
    HandbookRuleDefinition(
        "missing_payment_on_completed_job",
        "Missing payment on completed job",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: diagnostic fee and payments",
        "Completed jobs should not leave unpaid balances without a documented reason.",
        "high",
        ("status", "payments"),
        ("ServiceTitan invoices", "ServiceTitan payments"),
        AVAIL_PARTIAL,
        "For closed jobs with a positive invoice total, require paid status, zero balance, or positive payment.",
        "Invoice is paid, balance is zero, or payment total is positive.",
        "Completed job has a positive invoice total and no visible payment/paid signal.",
        "Payment fields are unavailable.",
        "accounting/office",
        "Collect payment, correct the payment record, or document approved billing terms.",
    ),
    HandbookRuleDefinition(
        "missing_follow_up_task_when_follow_up_needed",
        "Missing follow-up task when follow-up needed",
        "Follow-up / Escalation Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: post-call",
        "Follow-up flags without reminders create dropped customer commitments.",
        "medium",
        ("notes",),
        ("ServiceTitan job notes", "ServiceTitan reminders/tasks when available"),
        AVAIL_PARTIAL,
        "When notes indicate follow-up is needed, require a follow-up task/reminder indicator.",
        "No follow-up is needed, or a follow-up task/reminder exists.",
        "Follow-up is indicated but no task/reminder evidence exists.",
        "Notes or reminder/task source is unavailable.",
        "dispatcher channel",
        "Create the follow-up task/reminder and document the owner and due date.",
    ),
    HandbookRuleDefinition(
        "special_order_missing_required_notes",
        "Special-order missing required notes",
        "Follow-up / Escalation Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: special-order parts / future work",
        "Special-order notes need enough detail for parts tracking and customer updates.",
        "high",
        ("notes",),
        ("ServiceTitan job notes", "ServiceTitan purchase orders"),
        AVAIL_PARTIAL,
        "When special order is detected, require configured note fields.",
        "No special order is detected, or all required note fields are present.",
        "Special order is detected and one or more required fields are missing.",
        "Notes and PO text are unavailable.",
        "warehouse/parts",
        "Add PO number, ordering date, employee, ETA, supply house, and supplier contact when available.",
    ),
    HandbookRuleDefinition(
        "special_order_missing_service_titan_reminder",
        "Special-order missing ServiceTitan reminder",
        "Follow-up / Escalation Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: special-order parts / future work",
        "A reminder prevents expected part arrivals from being missed.",
        "medium",
        ("notes",),
        ("ServiceTitan job notes", "ServiceTitan reminders/tasks when available"),
        AVAIL_UNKNOWN,
        "When special order is detected, require reminder evidence if reminders/tasks are exposed.",
        "No special order is detected, or reminder evidence exists.",
        "Special order is detected and reminder source confirms no reminder.",
        "Reminder/task source is not integrated.",
        "warehouse/parts",
        "Create the expected part arrival reminder in ServiceTitan or the approved task system.",
    ),
    HandbookRuleDefinition(
        "missing_downpayment_for_special_order",
        "Missing downpayment for special order",
        "Follow-up / Escalation Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: special-order parts / future work",
        "Special-order deposits reduce unrecoverable material cost risk.",
        "high",
        ("invoice_line_items", "payments", "notes"),
        ("ServiceTitan invoices", "ServiceTitan invoice items", "ServiceTitan payments", "ServiceTitan notes"),
        AVAIL_PARTIAL,
        "When special order is detected, require deposit/downpayment or payment evidence.",
        "No special order is detected, or downpayment/payment evidence exists.",
        "Special order is detected without downpayment/payment evidence.",
        "Invoice/payment or notes source is unavailable.",
        "accounting/office",
        "Collect the deposit/downpayment or document the approved exception.",
    ),
    HandbookRuleDefinition(
        "lead_turnover_missing_required_documentation",
        "Lead turnover missing required documentation",
        "Service Call Handbook Audit",
        "FINAL SERVICE CALL HANDBOOK.pdf: lead turnover",
        "Lead turnovers need enough HHR, ductwork, options, equipment, and notes detail for sales handoff.",
        "high",
        ("notes", "hhr", "photos", "estimates", "equipment"),
        ("ServiceTitan notes", "ServiceTitan forms", "ServiceTitan attachments", "ServiceTitan estimates", "ServiceTitan equipment"),
        AVAIL_PARTIAL,
        "When lead turnover is detected, require HHR, photos, options, equipment, and turnover notes.",
        "No lead turnover is detected, or required handoff documentation exists.",
        "Lead turnover is detected and one or more required evidence categories are missing.",
        "One or more required evidence sources are unavailable.",
        "technician manager",
        "Complete HHR, equipment/photos, option sheet, ductwork/insulation notes, and lead turnover notes.",
    ),
    HandbookRuleDefinition(
        "po_received_not_reconciled",
        "PO received but not reconciled",
        "Ply / PO Materials Audit",
        "ply-plumbing-dispatcher-handbook-v4 (1).pdf: reconciliation",
        "Received POs must be reconciled so job cost and supplier invoice data stay accurate.",
        "high",
        ("purchase_orders", "po_reconciliation"),
        ("ServiceTitan purchase orders", "Future Ply API"),
        AVAIL_PARTIAL,
        "Fail when a received PO is visible and not reconciled.",
        "No received unreconciled PO exists.",
        "At least one received PO is not reconciled.",
        "PO or reconciliation source is unavailable.",
        "warehouse/parts",
        "Reconcile the received PO against the supplier invoice and confirm job attribution.",
    ),
    HandbookRuleDefinition(
        "po_missing_vendor_document",
        "PO missing vendor document",
        "Ply / PO Materials Audit",
        "ply-plumbing-dispatcher-handbook-v4 (1).pdf: PO receiving",
        "Vendor document numbers connect received parts to supplier paperwork.",
        "high",
        ("purchase_orders", "po_vendor_document"),
        ("ServiceTitan purchase orders", "Future Ply API"),
        AVAIL_PARTIAL,
        "Fail when a received PO has no vendor document number.",
        "Received POs have vendor document numbers.",
        "At least one received PO lacks a vendor document number.",
        "PO or vendor document source is unavailable.",
        "warehouse/parts",
        "Add vendor invoice/packing slip/document number to the PO.",
    ),
    HandbookRuleDefinition(
        "po_missing_attachments",
        "PO missing attachments",
        "Ply / PO Materials Audit",
        "ply-plumbing-dispatcher-handbook-v4 (1).pdf: PO receiving",
        "Uploaded paperwork supports receiving, reconciliation, and later vendor claims.",
        "medium",
        ("purchase_orders", "po_attachments"),
        ("ServiceTitan purchase orders", "Future Ply API"),
        AVAIL_PARTIAL,
        "Fail when a received PO has no uploaded paperwork/attachments.",
        "Received POs have one or more attachments.",
        "At least one received PO lacks attachments.",
        "PO or attachment source is unavailable.",
        "warehouse/parts",
        "Upload vendor paperwork, pickup paperwork, or order confirmation to the PO.",
    ),
    HandbookRuleDefinition(
        "po_not_synced_to_service_titan",
        "PO not synced to ServiceTitan",
        "Ply / PO Materials Audit",
        "ply-plumbing-dispatcher-handbook-v4 (1).pdf: ServiceTitan sync",
        "Ply is the source of truth for physical movement, but ServiceTitan must receive synced PO records.",
        "high",
        ("ply_purchase_orders", "purchase_orders"),
        ("Future Ply API", "ServiceTitan purchase orders"),
        AVAIL_UNAVAILABLE,
        "Compare future Ply POs to ServiceTitan POs for the job.",
        "Every applicable Ply PO has a matching ServiceTitan PO.",
        "A Ply PO lacks a matching ServiceTitan PO.",
        "Ply integration is unavailable.",
        "warehouse/parts",
        "Use + Create Purchase Order in ST or resolve the Ply/ST sync issue.",
    ),
    HandbookRuleDefinition(
        "ply_st_material_sync_blocked",
        "Ply/ST material sync blocked",
        "Ply / PO Materials Audit",
        "ply-plumbing-dispatcher-handbook-v4 (1).pdf: escalations",
        "Blocked sync causes inventory, purchasing, and job costing to diverge.",
        "high",
        ("ply_sync_status",),
        ("Future Ply API",),
        AVAIL_UNAVAILABLE,
        "Read future Ply sync status/error state.",
        "Ply sync is healthy or no blocked sync exists.",
        "Ply reports a blocked ServiceTitan sync.",
        "Ply integration is unavailable.",
        "Ali/operations escalation",
        "Escalate the blocked Ply/ST sync with job and PO identifiers.",
    ),
    HandbookRuleDefinition(
        "scope_change_missing_escalation_note",
        "Scope change missing escalation note",
        "Follow-up / Escalation Audit",
        "ply-plumbing-dispatcher-handbook-v4 (1).pdf: escalations",
        "Scope changes need manager/operations visibility before billing and materials drift.",
        "high",
        ("notes",),
        ("ServiceTitan notes",),
        AVAIL_PARTIAL,
        "When scope-change language is detected, require Dastan/manager/ops escalation language.",
        "No scope change is detected, or escalation note exists.",
        "Scope change is detected without escalation evidence.",
        "Notes source is unavailable.",
        "dispatcher channel",
        "Add the Dastan/operations escalation note and confirm the approved scope change.",
    ),
    HandbookRuleDefinition(
        "cancellation_after_materials_missing_escalation",
        "Cancellation after materials missing escalation",
        "Follow-up / Escalation Audit",
        "ply-plumbing-dispatcher-handbook-v4 (1).pdf: escalations",
        "Cancellations after install/materials ordered can create unrecovered cost and supplier issues.",
        "critical",
        ("notes",),
        ("ServiceTitan notes", "ServiceTitan purchase orders"),
        AVAIL_PARTIAL,
        "When cancellation-after-materials language is detected, require escalation evidence.",
        "No cancellation-after-materials is detected, or escalation note exists.",
        "Cancellation-after-materials is detected without escalation evidence.",
        "Notes/PO source is unavailable.",
        "Ali/operations escalation",
        "Escalate immediately and document material disposition, customer decision, and billing plan.",
    ),
    HandbookRuleDefinition(
        "defective_part_missing_warranty_claim_data",
        "Defective part missing warranty claim data",
        "Follow-up / Escalation Audit",
        "ply-plumbing-dispatcher-handbook-v4 (1).pdf: escalations",
        "Defective installed parts require warranty claim evidence for vendor recovery.",
        "medium",
        ("notes",),
        ("ServiceTitan notes", "ServiceTitan attachments", "Future Ply API"),
        AVAIL_PARTIAL,
        "When defective-part language is detected, require warranty claim/RMA evidence.",
        "No defective part is detected, or warranty claim/RMA evidence exists.",
        "Defective part is detected without warranty claim/RMA evidence.",
        "Notes source is unavailable.",
        "warehouse/parts",
        "Add vendor warranty claim/RMA data and supporting photos or paperwork.",
    ),
)

HANDBOOK_RULES_BY_ID = {rule.rule_id: rule for rule in HANDBOOK_RULES}
